bestguide/urls.py
from django.urls import path
from . import views

app_name = 'bestguide'

urlpatterns = [
    path('', views.besthome, name='besthome'),
    path('testing/', views.testing, name='testing'),
    path('motd/', views.motd, name='motd'),


]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:post_id>/', views.detail, name='detail'),

]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.vibes, name='vibes'),
    path('portfolio/', views.home, name='portfolio'),
    path('blog/', include('blog.urls')),
    # mothers day project
    # path('fabis/', views.fabis, name='fabis'),
    #bestbuy guide
    path('bestguide/', include('bestguide.urls')),
    #amys nails page
    # path('amyloks/', views.amynails, name='amynails'),
    #javascript bs
    path('cool/', views.particles, name='particles'),
    #2nd portfolio page
    path('about/', views.about, name='about'),
    path('resume/', views.resume, name='resume'),
    path('vboard/', views.vboard, name='vboard'),




]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

portfolio/views.py
from django.shortcuts import render
import random
from .models import Project
from django.http import HttpResponse

fortuneList = [
    "Your dreams are the key to unlocking your true potential.",
    "Diamonds are a symbol of your inner strength and resilience.",
    "The universe has great things in store for you. Trust and Enjoy the journey.",
    "This is the sign you've been searching for. Everything is aligning itself for you.",
    "The universe conspires to bring you closer to your dreams.",
    "Your visions are the bridge between imagination and reality.",
    "The magic you're looking for, is in the work you're avoiding.",
]

def home(request):

    return render(request, 'portfolio/home.html')


def fabis(request):
    return render(request, 'portfolio/fabis.html')


def amynails(request):
    return render(request, 'portfolio/amynails.html')


def vibes(request):
    fortune = random.choice(fortuneList)
    context = {"fortune": fortune}
    return render(request, 'portfolio/about.html', context)


def particles(request):
    return render(request, 'portfolio/particles.html')


def about(request):
    return render(request, 'portfolio/vibes.html')


def resume(request):
    return render(request, 'portfolio/resume.html')


def vboard(request):
    return render(request, 'portfolio/vboard.html')

portfolio/templates/portfolio/3Dlogo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'portfolio/css/3Dlogo.css' %}">
    <title>3D</title>
</head>
<body>
<div class="thumb">
	  <a href="#">
      <span>free your mind</span>
	  </a>

</div>
</body>
</html>

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Victor Calvario. Universal Vibes. A place of infinite possibilities and alternate realities."/>

    <!-- Bootstrap CSS -->
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">-->

<!--    <link rel="stylesheet" href="{% static 'portfolio/css/custom.css' %}">-->
<!--    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">-->
    <link rel="stylesheet" href="{% static 'portfolio/css/about.css' %}" />
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aladin&family=Yellowtail&family=Raleway+Dots&family=Cinzel+Decorative:wght@700&family=Thasadith&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static 'portfolio/images/LogoFinalForever.png' %}">



    <title>We Are Creators</title>




  </head>

<body>
<nav class="navbar navbar-expand-xl bg-primary text-uppercase fixed-top" id="mainNav">
            <div class="container text-center">
                <img style="margin:0 5px;" src="https://www.vcalvario.com/static/portfolio/images/LogoFinalForever.png" width="60" height="60" alt="logo"/>
                <a class="navbar-brand" style="margin:0 0 0 5px" href="{% url 'vibes' %}">Diamond Dream<br />Visionaries &trade;</a>

                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">

                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'vibes' %}">Portfolio</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'about' %}">Projects</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'blog:all_blogs' %}">Blogs</a></li>
<!--                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'bestguide:besthome' %}">Bestguide</a></li>-->
<!--                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'resume' %}">Resume</a></li>-->

                    </ul>
                </div>
            </div>
        </nav>



<section class="container text-center">

 {% block content %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</section>

  <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
<!--<footer>-->
<!--  Copyright &#169; 2021 CalvarioV &trade; All rights reserved.-->
<!--</footer>-->
</body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}

<nav id="topNav" class="navbar navbar-expand-md navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'vibes' %}">
        <img src="{% static 'portfolio/images/cvlogo3.png' %}" width="60" height="60" class="d-inline-block align-top" alt="vcalvario logo">
      </a>


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'vibes' %}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'bestguide:besthome' %}">BestGuide</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% static 'portfolio/Py4eCer.pdf' %}">Py4e</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% static 'portfolio/Dj4eCer.pdf' %}">Dj4e</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active1" href="{% url 'portfolio' %}" target="_self">Portfolio</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blogs</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


<div class="row justify-content-center my-3">
  <div class="col-10">

      <img src="{% static 'portfolio/images/neonvika2.jpg' %}" class="img-fluid round" alt="Victor Calvario"/>

  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
      <h1 id="hometext" class="font-weight-bold">Victor Calvario<br>Commander<br>-in-<br>Chief<br>👨🏻‍💻</h1>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>




<div class="row justify-content-center my-3">
  <div class="col-lg-8">
      <h2>Ask and you shall receive.</h2>
      <img src="{% static 'portfolio/babygrootnike.jpeg' %}" class="img-fluid mb-2 round" alt="Baby Groot"/>
      <img src="{% static 'portfolio/images/infiniteintelligencetake2.jpg' %}" class="img-fluid mb-2 intro round" alt="infiniti car"/>
      <div class="w3-panel w3-leftbar w3-light-grey round">
            <span class="w3-xlarge w3-serif"><i>"Whatever you ask for in prayer, believe that you have received it, and it will be yours."</i></span>
          <br>
          <b>Mark 11:24</b>
      </div>
  </div>
</div>

<hr>

<div class="container">
    <div class="row justify-content-center">
        <iframe src="https://www.youtube.com/embed/BpTnDubX1_w" width="500" height="350"></iframe>

        <div class="col-lg-4 col-md-6 webby">
<!--            <button type="button" class="collapsible">Video Highlights</button>-->
<!--                <div class="content">-->
<!--                    <p>-->
<!--                        <b>1)</b> It is our attitude at the beginning of our task that more than anything will affect its successful outcome<br>-->
<!--                        <b>2)</b> It is our attitude toward life which will determine life’s attitude towards us<br>-->
<!--                        <b>3)</b> We are interdependent it is impossible to succeed without others, and it is our attitude towards others that will determine others' attitude towards us<br>-->
<!--                        <b>4)</b> Before a person can achieve the kind of life he wants he must become that kind of individual<br>-->
<!--                        <b>5)</b> The higher you go in any organization of value the better the attitude you’ll find<br>-->
<!--                        <b>6)</b> Your mind can only hold one though at a time and since there is nothing to gain from being negative, hold positive thoughts<br>-->
<!--                        <b>7)</b> The deepest craving in human beings is to be needed, feel important and appreciated, give it to them, and they will return it to you<br>-->
<!--                        <b>8)</b> Look for the best in new ideas, as someone said, I've never met a person I couldn't learn something from<br>-->
<!--                        <b>9)</b> Don’t waste valuable time broadcasting personal problems<br>-->
<!--                        <b>10)</b> Don’t talk about your health unless it’s good<br>-->
<!--                        <b>11)</b> Radiate the attitude of well-being, of confidence, of a person who knows where he is going this will inspire those around you<br>-->
<!--                        <b>12)</b> For the next 30 days treat anyone who you come in contact with as the most important person on earth<br>-->
<!--                    </p>-->
<!--                </div>-->

            <hr>

            <button type="button" class="collapsible">As A Man Thinketh</button>
                <div class="content">
                    <span>
                        The aphorism, "As a man thinketh in his heart so is he," not only embraces the whole of a man's being, but is so
                        comprehensive as to reach out to every condition and circumstance of his life. A man is literally what he thinks,
                        his character being the complete sum of all his thoughts.
                        As the plant springs from, and could not be without, the seed, so every act of a man springs from the hidden
                        seeds of thought, and could not have appeared without them. This applies equally to those acts called
                        "spontaneous" and "unpremeditated" as to those which are deliberately executed.
                        Act is the blossom of thought, and joy and suffering are its fruits; thus does a man garner in the sweet and bitter
                        fruitage of his own husbandry.
                    </span>
                </div>

        </div>
    </div>
</div>
<hr>
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <a href="https://www.vcalvario.com"><img src="{% static 'portfolio/images/CVLogo3D.png' %}" class="img-fluid mb-2 intro round" width="50%" alt="vcalvario logo"/></a>
        </div>
    </div>
</div>
<br>

<script>
    var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}

</script>
{% endblock %}

portfolio/templates/portfolio/particles.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'portfolio/css/particles.css' %}">
    <link rel="icon" type="image/png" href="{% static 'portfolio/CVLogo2.png' %}">
    <title>Particles</title>
</head>
<body>

<script src="{% static 'portfolio/js/three.js' %}"></script>
<script type="text/javascript" src="{% static 'portfolio/js/particles.js' %}"></script>
<script type="x-shader/x-vertex" id="vertexshader">

  attribute float size;
  attribute vec3 customColor;
  varying vec3 vColor;

  void main() {

    vColor = customColor;
    vec4 mvPosition = modelViewMatrix * vec4( position, 1.0 );
    gl_PointSize = size * ( 300.0 / -mvPosition.z );
    gl_Position = projectionMatrix * mvPosition;

  }

</script>
<script type="x-shader/x-fragment" id="fragmentshader">

 uniform vec3 color;
 uniform sampler2D pointTexture;

 varying vec3 vColor;

 void main() {

   gl_FragColor = vec4( color * vColor, 1.0 );
   gl_FragColor = gl_FragColor * texture2D( pointTexture, gl_PointCoord );

 }
</script>

<div id="magic"></div>
<div class="playground">
  <div class="bottomPosition">
      <a href="https://www.vcalvario.com" target="_blank"><img src="https://www.vcalvario.com/static/portfolio/CVLogo2.png" width=40px/></a>

        <h1 class="special">Victor Calvario <br><span class="minText">Fullstack Developer && UI/UX designer.</span></h1>
  </div>
</div>

</body>
</html>

portfolio/templates/portfolio/resume.html
{% load static %}
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/portfolio/css/resume.css">
    <title>Victor Calvario - Resume</title>
  </head>
  <body>

    <div class="container">
        <div class="image-container">
    <img id="themeImage" src="https://calvariov.pythonanywhere.com/site/subfolder/myquotecvlogoFinal.jpg" alt="Descriptive Alt Text">

</div>

        <hr>
      <h1>Victor Manuel Calvario</h1>
      <div class="contact">
          <span>calvario24@icloud.com</span> |
        <span>Downey, California</span>
      </div>

<!--        <button class="vbutton" id="dark-mode-btn">Vision Edition</button>-->
        <div>
            <label class="switch">
        <input type="checkbox" id="dark-mode-btn">
        <span class="slider round"></span>
        </label>
        </div>
        <hr>
      <h2>Premium Sales Consultant<br> Graphic & Web Designer</h2>

      <h3>Professional Summary</h3>
      <p>
        Dynamic and results-driven professional with a diverse background in sales, leadership, and technical expertise. I began my career as a Frontier door-to-door sales representative, where I honed my communication and customer engagement skills. Progressing to a lead position at a warehouse, I developed strong leadership and organizational abilities, overseeing operations and ensuring efficiency.

Transitioning back to a salesman role for appliances, I leveraged my product knowledge and sales acumen to drive revenue growth and enhance customer satisfaction. As a Verizon activation specialist, I mastered technical sales, providing seamless activation services and exceptional customer support. My experience further expanded as a home theater Sony VPL specialist, where I combined technical proficiency with sales to deliver customized home theater solutions.

Currently, I serve as a premium generalist, applying my extensive sales, leadership, and technical expertise to provide high-level support and drive business success. My career trajectory demonstrates a consistent track record of achievement and adaptability across various roles and industries.
      </p>
      <hr>



      <h2>Work Experience</h2>
      <!--        position # Premium Home Theater Specialist 6  -->
        <div>
            <h4>Premium Home Theater Specialist</h4>
      <p>Best Buy - July 2024 to Present</p>
      <ul>
        <li>Ensured the department consistently met and exceeded daily revenue targets, closely monitoring sales performance and implementing strategies to drive growth</li>
        <li>Maintained the department's alignment with previous years' goals, striving for continuous improvement and fostering a culture of business growth and development</li>
        <li>Developed and implemented effective selling strategies, such as the "Good, Better, Best" approach, across all brands in the home theater department to cater to diverse customer preferences and increase sales</li>
      </ul>
        </div>


      <!--        position # Sony VPL 5  -->
        <div>
            <h4>Sony VPL</h4>
      <p>Best Buy - Nov 2023 to June 2024</p>
      <ul>
        <li>Educated customers on the advanced features and benefits of Sony's high-definition televisions and home theater systems, enabling them to make informed purchasing decisions</li>
        <li>Actively promoted Sony's range of TVs, emphasizing their superior picture quality, innovative technology, and overall performance</li>
        <li>Developed a <a href="{% url 'bestguide:besthome' %}">Web App</a> to showcase different television models, providing on-demand information about features, prices, and size availability, thereby maximizing sales and enhancing customer engagement</li>
      </ul>
        </div>

      <!--        position # Verizon VPL 4  -->
        <div>
            <h4>Verizon VPL</h4>
      <p>Best Buy - Nov 2021 to Nov 2023</p>
      <ul>
        <li>Create customers new account and activate new lines, ensuring a smooth customer experience and seamless transition from old to new devices</li>
        <li>Provide expert advice to customers, helping them choose the best options for their needs</li>
        <li>Utilized in-depth product knowledge to upsell and cross-sell additional services, resulting in increased revenue</li>
      </ul>
        </div>

      <!--        position # Appliance Generalist 3  -->
        <div>
            <h4>Appliance Generalist</h4>
      <p>Best Buy - May 2021 to Nov 2021</p>
      <ul>
        <li>Assisted customers in building comprehensive kitchen packages, ensuring selections met their specific needs and preferences</li>
        <li>Provided various options tailored to specific measurements and requirements, offering expert advice to optimize space and functionality</li>
        <li>Created detailed orders, coordinating entire installation services to ensure seamless and satisfactory customer experiences</li>
      </ul>
        </div>

      <!--        position # Warehouse Lead 2  -->
        <div>
            <h4>Warehouse Lead</h4>
      <p>Various Companies - 2019 to 2021</p>
      <ul>
        <li>Operated forklifts and electric pallet jacks</li>
        <li>Utilize RF Scanner and the Synapse program to assign and complete orders</li>
        <li>Managed team to complete daily orders to guarantee timely and accurate deliveries</li>
      </ul>
        </div>

      <!--        position # Telecom 1  -->
        <div>
            <h4>Customer Service Representative</h4>
      <p>Telecom Communications - 2017 to 2019</p>
      <ul>
        <li>Successfully sign up new accounts for telecom services</li>
        <li>Resolved customer complaints and inquiries promptly, maintaining a high level of customer
satisfaction</li>
        <li>Collaborate with team members to share sales strategies and best practices, contributing to a positive and supportive work environment</li>
      </ul>
        </div>






      <hr>
      <h2>Skills</h2>
      <ul class="skills-list">
        <li>
            <span>Sales</span>
            <div class="progress-bar-container">
                <div class="progress-bar" data-value="90"></div>
            </div>
        </li>
        <li>
            <span>Animation and Video</span>
            <div class="progress-bar-container">
                <div class="progress-bar" data-value="70"></div>
            </div>
        </li>
        <li>
            <span>Photoshop</span>
            <div class="progress-bar-container">
                <div class="progress-bar" data-value="80"></div>
            </div>
        </li>

        <li>
            <span>Front-End Development</span>
            <div class="progress-bar-container">
                <div class="progress-bar" data-value="85"></div>
            </div>
        </li>
        <li>
            <span>Back-End Development</span>
            <div class="progress-bar-container">
                <div class="progress-bar" data-value="65"></div>
            </div>
        </li>
        <li>
            <span>Awesome 😎</span>
            <div class="progress-bar-container">
                <div class="progress-bar" data-value="100"></div>
            </div>
        </li>
    </ul>


      <hr>
      <a href="{% static 'portfolio/Py4eCer.pdf' %}">Python Certificate</a><br><br>
      <a href="{% static 'portfolio/Dj4eCer.pdf' %}">Django Certificate</a><br>
      <hr>

    </div>

    <footer>
  <a href="{% url 'vibes' %}">
    <img src="https://www.vcalvario.com/static/portfolio/images/LogoFinalForever.png" alt="Home Icon">
  </a>
</footer>

    <script>

    </script>
    <script src="{% static 'portfolio/js/resume1.js' %}"></script>
  </body>
</html>

portfolio/templates/portfolio/vibes.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <meta name="description" content="Victor Calvario. Universal Vibes. A place of infinite possibilities and alternate realities."/>
    <link rel="stylesheet" href="{% static 'portfolio/css/vibes.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" type="image/png" href="https://www.vcalvario.com/static/portfolio/images/LogoFinalForever.png">
    <title>vcalvario.com</title>
</head>

<body>


<br>

    <div class="masthead mt-4">

        <div class="text-center mt-4 mb-4">
                    <a class="btn btn-md btn-outline-danger" href="{% url 'bestguide:besthome' %}">
                        <i class="fas fa-book-reader me-2"></i>
                        Bestguide
                    </a>
        </div>
        <div class="text-center mt-4 mb-4">
                    <a class="btn btn-md btn-outline-danger" href="https://calvariov.pythonanywhere.com/generator/">
                        <i class="fa fa-key me-2"></i>
                        Password Generator
                    </a>
        </div>

<div class="masthead text-white text-center mt-4 mb-4">
                    <div class="coming-soon-text grads">More apps coming soon!</div>
        </div>



        <div class="img-border">
            <a href="#"><img src="https://calvariov.pythonanywhere.com/site/subfolder/spacefloatddvTCgiphy.gif" class="w-100 img-fluid" alt="spacefloat"/></a>
        </div>

        <div class="neonbody">
            <div class="neontext">creators of our own realities.
            </div>
        </div>

    </div>


</body>
{% endblock %}




</html>